FROM golang:1.25-alpine

WORKDIR /app

COPY ./ /app/

EXPOSE $PORT

RUN apk update &&\
    apk add --no-cache ffmpeg &&\
    rm -rf /var/cache/apk/*

CMD ["sh", "-c", "go build -o ./bin/server ./cmd/server/main.go && ./bin/server"]